version: 0.1
phases:
  yarn:
    commands:
      - echo Installing yarn
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json
