version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16.13.2
  pre_build:
    commands:
      - echo Installing yarn
      - npm install -g yarn
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json
