version: '3.8'

services:
  dev:
    links:
      - postgres:postgres
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile

    command: npm run start:debug
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgis/postgis
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
  keycloak:
    container_name: keycloak
    links:
      - postgres:postgres
    image: dmitriynoa/custom-keycloak:0.0.1
    restart: always
    command:
      - start-dev
    ports:
      - "8888:8080"
    volumes:
      - /data/keycloak:/data/keycloak
    env_file:
      - .env

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "9999:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
