apiVersion: v1
kind: Secret
metadata:
  name: extensions-api-secret
  namespace: local-hero
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
type: Opaque
