apiVersion: v1
kind: Service
metadata:
  name: keycloak-development-service
  namespace: local-hero
  labels:
    app: keycloak-deployment
spec:
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 8080
  selector:
    app: keycloak-deployment
