apiVersion: v1
kind: Service
metadata:
  name: keycloak-development-service
  namespace: local-hero
  labels:
    app: keycloak-deployment
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: keycloak-deployment
