apiVersion: v1
kind: ConfigMap
metadata:
  name: local-hero-config
  namespace: local-hero
  labels:
    app: local-hero-config
data:
  POSTGRES_DB: "local-hero"
  POSTGRES_HOST: "local-hero-api-postgres"
  POSTGRES_PORT: "5432"
  PORT: "3000"
  NODE_ENV: "production"
  KEYCLOAK_CLIENT_ID: "local-hero-api"
  KEYCLOAK_ADMIN_CLIENT_ID: "admin-cli"
  KEYCLOAK_BASE_URL: "http://keycloak-development-service.local-hero.svc.cluster.local:7777"
  KEYCLOAK_REALM_NAME: "master"
  KEYCLOAK_TOKEN_URL: "http://keycloak-development-service.local-hero.svc.cluster.local:7777/realms/hero/protocol/openid-connect/token"
  AWS_S3_BUCKET: "local-hero-images"
  KEYCLOAK_PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_FRONTEND_URL: "https://auth.local-champion.com"
