apiVersion: v1
kind: Service
metadata:
  name: local-hero-api
  namespace: local-hero
spec:
  selector:
    app: local-hero-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-hero-api
  namespace: local-hero
  labels:
    app: local-hero-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-hero-api
  template:
    metadata:
      labels:
        app: local-hero-api
    spec:
      containers:
        - name: local-hero-api
          image: dmitriynoa/test-api:0.0.1
          envFrom:
            - secretRef:
                name: local-hero-api-secret
            - configMapRef:
                name: local-hero-config
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      serviceAccountName: default
